global using OpenTK.Mathematics;
global using Patchwork;
global using Patchwork.PECS;
global using Patchwork.Render;
global using Patchwork.Render.Objects;
global using Patchwork.Audio;
global using Patchwork.Audio.Objects;
global using Patchwork.Input;
global using Patchwork.Input.Objects;
global using static Patchwork.Helper;